name: Check Links

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 5"

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run check-links script
        run: pnpm run check-links
